# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: E:/Users/Kyle/Documents/sr_proj_test/SDP/VHDL/Fullsystem1.1/source/ipcores/ipcores/vga/clocks/vga_clk.xci
# IP: The module: 'vga_clk' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: e:/Users/Kyle/Documents/sr_proj_test/SDP/VHDL/Fullsystem1.1/source/ipcores/ipcores/vga/clocks/vga_clk_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'vga_clk'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: e:/Users/Kyle/Documents/sr_proj_test/SDP/VHDL/Fullsystem1.1/source/ipcores/ipcores/vga/clocks/vga_clk.xdc
# XDC: The top module name and the constraint reference have the same name: 'vga_clk'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: e:/Users/Kyle/Documents/sr_proj_test/SDP/VHDL/Fullsystem1.1/source/ipcores/ipcores/vga/clocks/vga_clk_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'vga_clk'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: E:/Users/Kyle/Documents/sr_proj_test/SDP/VHDL/Fullsystem1.1/source/ipcores/ipcores/vga/clocks/vga_clk.xci
# IP: The module: 'vga_clk' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: e:/Users/Kyle/Documents/sr_proj_test/SDP/VHDL/Fullsystem1.1/source/ipcores/ipcores/vga/clocks/vga_clk_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'vga_clk'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: e:/Users/Kyle/Documents/sr_proj_test/SDP/VHDL/Fullsystem1.1/source/ipcores/ipcores/vga/clocks/vga_clk.xdc
# XDC: The top module name and the constraint reference have the same name: 'vga_clk'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: e:/Users/Kyle/Documents/sr_proj_test/SDP/VHDL/Fullsystem1.1/source/ipcores/ipcores/vga/clocks/vga_clk_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'vga_clk'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
