# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: E:/Users/Kyle/Documents/sr_proj_test/SDP/VHDL/Fullsystem1.1/source/ipcores/ipcores/transmission_system/uartloader_fifo/uartloader_fifo.xci
# IP: The module: 'uartloader_fifo' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: e:/Users/Kyle/Documents/sr_proj_test/SDP/VHDL/Fullsystem1.1/source/FinalSDP.gen/sources_1/ip/uartloader_fifo/uartloader_fifo.xdc
# XDC: The top module name and the constraint reference have the same name: 'uartloader_fifo'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: e:/Users/Kyle/Documents/sr_proj_test/SDP/VHDL/Fullsystem1.1/source/FinalSDP.gen/sources_1/ip/uartloader_fifo/uartloader_fifo_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'uartloader_fifo'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: E:/Users/Kyle/Documents/sr_proj_test/SDP/VHDL/Fullsystem1.1/source/ipcores/ipcores/transmission_system/uartloader_fifo/uartloader_fifo.xci
# IP: The module: 'uartloader_fifo' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: e:/Users/Kyle/Documents/sr_proj_test/SDP/VHDL/Fullsystem1.1/source/FinalSDP.gen/sources_1/ip/uartloader_fifo/uartloader_fifo.xdc
# XDC: The top module name and the constraint reference have the same name: 'uartloader_fifo'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: e:/Users/Kyle/Documents/sr_proj_test/SDP/VHDL/Fullsystem1.1/source/FinalSDP.gen/sources_1/ip/uartloader_fifo/uartloader_fifo_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'uartloader_fifo'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
