# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: E:/Users/Kyle/Documents/sr_proj_test/SDP/VHDL/Fullsystem1.1/source/ipcores/ipcores/vga/fifo/fifo_generator_0.xci
# IP: The module: 'fifo_generator_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: e:/Users/Kyle/Documents/sr_proj_test/SDP/VHDL/Fullsystem1.1/source/ipcores/ipcores/vga/fifo/fifo_generator_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'fifo_generator_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: e:/Users/Kyle/Documents/sr_proj_test/SDP/VHDL/Fullsystem1.1/source/ipcores/ipcores/vga/fifo/fifo_generator_0_clocks.xdc
# XDC: The top module name and the constraint reference have the same name: 'fifo_generator_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: e:/Users/Kyle/Documents/sr_proj_test/SDP/VHDL/Fullsystem1.1/source/ipcores/ipcores/vga/fifo/fifo_generator_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'fifo_generator_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: E:/Users/Kyle/Documents/sr_proj_test/SDP/VHDL/Fullsystem1.1/source/ipcores/ipcores/vga/fifo/fifo_generator_0.xci
# IP: The module: 'fifo_generator_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: e:/Users/Kyle/Documents/sr_proj_test/SDP/VHDL/Fullsystem1.1/source/ipcores/ipcores/vga/fifo/fifo_generator_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'fifo_generator_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: e:/Users/Kyle/Documents/sr_proj_test/SDP/VHDL/Fullsystem1.1/source/ipcores/ipcores/vga/fifo/fifo_generator_0_clocks.xdc
# XDC: The top module name and the constraint reference have the same name: 'fifo_generator_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: e:/Users/Kyle/Documents/sr_proj_test/SDP/VHDL/Fullsystem1.1/source/ipcores/ipcores/vga/fifo/fifo_generator_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'fifo_generator_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
